// components/PcapAnalyzer.jsx
// Uploads a PCAP file to the backend AI endpoint and renders the result.
// Uses VITE_API_BASE_URL — no hardcoded localhost.
// Displays the ML-generated attack distribution chart served from /ai-assets/.
import React, { useState } from "react";
import axios from "axios";

const API_BASE = import.meta.env.VITE_API_BASE_URL;

export default function PcapAnalyzer() {
  const [file,    setFile]    = useState(null);
  const [result,  setResult]  = useState(null);
  const [loading, setLoading] = useState(false);
  const [error,   setError]   = useState(null);

  const handleFileChange = (e) => {
    setFile(e.target.files[0] || null);
    setResult(null);
    setError(null);
  };

  const handleAnalyze = async () => {
    if (!file) {
      setError("Please select a .pcap file first.");
      return;
    }

    const formData = new FormData();
    formData.append("pcap", file);

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await axios.post(`${API_BASE}/api/ai/analyze-pcap`, formData);
      setResult(res.data);
    } catch (err) {
      console.error("[PcapAnalyzer] Error:", err);
      setError(err.response?.data?.error || "Analysis failed. Check console for details.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="panel">
      <div className="panel-title">🔬 AI PCAP Analyzer</div>

      {/* File picker + analyze button */}
      <div className="file-row">
        <label className="file-label">
          📂 {file ? "Change file" : "Choose .pcap file"}
          <input type="file" accept=".pcap" onChange={handleFileChange} />
        </label>

        {file && (
          <span className="file-name" title={file.name}>{file.name}</span>
        )}
      </div>

      <button
        className="btn btn--primary"
        onClick={handleAnalyze}
        disabled={loading || !file}
      >
        {loading ? <><span className="spinner" /> Analyzing…</> : "Analyze"}
      </button>

      {/* Inline error */}
      {error && (
        <div className="error-banner" style={{ marginTop: "0.75rem" }}>
          ⚠ {error}
        </div>
      )}

      {/* Results */}
      {result && (
        <div className="pcap-result">
          {/* Attack distribution chart generated by the ML model */}
          {result.chart_file && (
            <div className="pcap-result-section">
              <div className="pcap-section-title">Attack Distribution Chart</div>
              <img
                src={`${API_BASE}/ai-assets/${result.chart_file}?t=${Date.now()}`}
                alt="Attack distribution chart"
                className="pcap-chart-img"
                onError={(e) => { e.currentTarget.style.display = "none"; }}
              />
            </div>
          )}

          {/* Summary counts */}
          <div className="pcap-result-section">
            <div className="pcap-section-title">Attack Summary</div>
            <pre className="pcap-pre">{JSON.stringify(result.summary, null, 2)}</pre>
          </div>

          {/* Per-packet report */}
          {Array.isArray(result.report) && result.report.length > 0 && (
            <div className="pcap-result-section">
              <div className="pcap-section-title">
                Detected Events ({result.report.length})
              </div>
              <ul className="pcap-list">
                {result.report.map((item, idx) => (
                  <li key={idx} className="pcap-item">
                    <span className="pcap-ip">{item.src_ip}</span>
                    <span className="pcap-arrow">→</span>
                    <span className="pcap-type">{item.attack_type}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
